const eventType = {
  RIDE_REQUESTED: "RIDE_REQUESTED",
  RIDE_AVAILABLE: "RIDE_AVAILABLE",
  RIDE_MATCHED: "RIDE_MATCHED",
  RIDE_ACCEPTED: "RIDE_ACCEPTED",
  RIDE_REJECTED: "RIDE_REJECTED",
};

module.exports = { eventType };
